server:
  port: 8000

student:
  id: 1003
  name: tom
  age: 30
  desc: ${student.name} is a student, ${student.age} years old this year

## 随机数
random:
  # 随机字符串
  value: ${random.value}
  # int
  number: ${random.int}
  number1: ${random.long}
  number2: ${random.int(10)}
  # 10-20的随机数
  number3: ${random.int[10,20]}

# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile
spring:
  profiles:
    active: prod